Better status handling

diff --git a/flint b/flint
--- a/flint
+++ b/flint
@@ -6,7 +6,6 @@ CONTRIBUTING=1
 LICENSE=1
 BOOTSTRAP=1
 TEST=1
-FIX=0
 
 cmd(){ echo `basename $0`; }
 
@@ -22,7 +21,6 @@ Checks a project for common sources of contributor friction
 -l, --license; Check for a project license
 -b, --bootstrap; Check for a bootstrap script
 -t, --test; Check for a test script
--f, --fix; Make suggested changes when able
 -v, --verbose; Verbose output
 --no-readme; Skip README check
 --no-contributing; Skip contributing guide check
@@ -32,59 +30,70 @@ Checks a project for common sources of contributor friction
 " | column -t -s ";"
 }
 
-# Error message
-error(){
-    echo "`cmd`: invalid option -- '$1'";
-    echo "Try '`cmd` -h' for more information.";
-    exit 1;
+# status variable
+STATUS=0
+
+function log {
+  echo "[${1}] ${2}"
+}
+
+function warning {
+  if [ $STATUS -lt 1 ]; then
+    STATUS=1
+  fi
+  log "WARNING" "${1}"
+}
+
+function error {
+  if [ $STATUS -lt 2 ]; then
+    STATUS=2
+  fi
+  log "ERROR" "${1}"
+}
+
+usage_error() {
+    error "`cmd`: invalid option -- '$1'. Try '`cmd` -h' for more information.";
 }
 
 readme(){
     if [ $README -eq 1 ]; then
-      echo "Checking for README..."
-
-      if [ $FIX -eq 1 ]; then
-        echo "Adding README"
+      if [[ -z $(find . -iname 'readme*') ]]; then
+        error "README not found"
+        log "FIXME" "Every project begins with a README. http://bit.ly/1dqUYQF"
       fi
     fi
 }
 
 contributing(){
     if [ $CONTRIBUTING -eq 1 ]; then
-      echo "Checking for contributing guide..."
-
-      if [ $FIX -eq 1 ]; then
-        echo "Adding CONTRIBUTING"
+      if [[ -z $(find . -iname 'contributing*') ]]; then
+        warning "Contributing guide not found"
+        log "FIXME" "Add a CONTRIBUTING guide for potential contributors. http://git.io/z-TiGg"
       fi
     fi
 }
 
 license(){
     if [ $LICENSE -eq 1 ]; then
-      echo "Checking for license..."
-
-      if [ $FIX -eq 1 ]; then
-        echo "Adding LICENSE"
+      if [[ -z $(find . -iname 'license*') ]]; then
+        error "License file not found"
+        log "FIXME" "Add a license to protect yourself and your users. http://choosealicense.com/"
       fi
     fi
 }
 
 bootstrap(){
     if [ $BOOTSTRAP -eq 1 ]; then
-      echo "Checking for bootstrap script..."
-
-      if [ $FIX -eq 1 ]; then
-        echo "Adding bootstrap script"
+      if [[ ! -d "script" || -z $(find . -iname 'script/bootstrap*') ]]; then
+        log "INFO" "A bootstrap script makes setup a snap. http://bit.ly/JZjVL6"
       fi
     fi
 }
 
 test_script(){
     if [ $TEST -eq 1 ]; then
-      echo "Checking for test script..."
-
-      if [ $FIX -eq 1 ]; then
-        echo "Adding test script"
+      if [[ ! -d "script" || -z $(find . -iname 'script/test*') ]]; then
+        log "INFO" "Make it easy to run the test suite regardless of project type. http://bit.ly/JZjVL6"
       fi
     fi
 }
@@ -102,15 +111,14 @@ for pass in 1 2; do
                 -l|--license)          LICENSE=1;;
                 -b|--bootstrap)        BOOTSTRAP=1;;
                 -t|--test)             TEST=1;;
-                -f|--fix)              FIX=1;;
                 --no-readme)           README=0;;
                 --no-contributing)     CONTRIBUTING=0;;
                 --no-license)          LICENSE=0;;
                 --no-bootstrap)        BOOTSTRAP=0;;
                 --no-test)             TEST=0;;
-                --*)                 error $1;;
+                --*)                 usage_error $1;;
                 -*)                  if [ $pass -eq 1 ]; then ARGS="$ARGS $1";
-                                     else error $1; fi;;
+                                     else usage_error $1; fi;;
                 esac;;
             *)  if [ $pass -eq 1 ]; then ARGS="$ARGS $1";
                 else error $1; fi;;
@@ -123,7 +131,19 @@ for pass in 1 2; do
 done
 
 readme
-contributing
 license
+contributing
 bootstrap
 test_script
+
+if [ $STATUS -eq 0 ]; then
+  log "OK" "All is well!"
+fi
+if [ $STATUS -eq 1 ]; then
+  log "WARNING" "Some warnings found."
+fi
+if [ $STATUS -eq 2 ]; then
+  log "CRITICAL" "Some critical problems found. Please fix right away!"
+fi
+
+exit $STATUS
